const { seed } = require('../../src/services/seeder');

exports.seed = (knex) => seed(
  knex,
  'amenities',
  [
    'swimming pool',
    'dishwasher',
    'wireless internet',
    'tv(cable)',
    'air conditioning',
    'fireplace',
    'heating available',
    'parking included',
    'parking optional',
    'towels',
    'hot tub',
    'breakfast included',
    'credit cards accepted',
    'accesible 24/7',
    'elevator in building',
    'housekeeping included',
    'pets welcome',
    'smoking not allowed',
    'laundry service included',
    'garden(private)',
    'elevator in building',
    'suitable for elderly or infirm',
    'suitable for events',
    'unsuitable for elderly or infirm',
    'wheelchair accessible',
    'wheelchair inaccesible',
    'Bathroom and laundry',
    'bed linen',
    'bidet',
    'hair dryer',
    'clothes dryer',
    'essentials',
    'iron & board',
    'shower',
    'towels',
    'hot tub',
    'washbasin',
    'washing machine',
    'blender',
    'child high chair',
    'coffe machine',
    'cooking utensiles',
    'dishwasher',
    'grill',
    'kitchenette',
    'kitchen stove',
    'allinclusive meal-plan',
    'full board meal-plan',
    'half board meal-plan',
    'microwave',
    'oven',
    'refrigerator',
    'rice steamer',
    'spices',
    'toaster',
    'water cooler',
    'water purifier',
    'air conditioning',
    'ceiling fans',
    'central heating',
    'electric heating',
    'fireplace',
    'floor heating',
    'heating available',
    'wood/tiled stove',
    'computer',
    'dvd-player',
    'fax',
    'broadband internet',
    'dial-up internet',
    'wireless internet',
    'piano',
    'stereo system',
    'telephone',
    'tv(antenna)',
    'tv(cable)',
    'tv(satelite)',
    'vaccume cleaner',
    'BBQ-charcoal grill',
    'bbq-electric',
    'bbq-gas',
    'deck  chairs',
    'bicycles',
    'boat',
    'canoe/kayak',
    'gated-community',
    'golf cart',
    'golf clubs',
    'motorboat',
    'garden(private)',
    'playground(private)',
    'porch(private)',
    'tennis court(private)',
    'sailboat',
    'shared garden',
    'shared playground',
    'shared porch',
    'tennis court(shared)',
    'parking garage',
    'parking lot',
    'on-street parking',
    'parking included',
    'parking optional',
    'roofed carport',
    'credit cards accepted',
    'accessible 24/7',
    'breakfast included',
    'children welcome',
    'housekeeper included',
    'housekeeper optional',
    'laundry service included',
    'laundry service optional',
    'low allergen environment',
    'pets welcome',
    'pets allowed only after arrangement',
    'pets not allowed',
    'smoking allowed',
    'smoking not allowed',
    'buzzer',
    'carbon monooxide detector',
    'doorman',
    'fire extinguisher',
    'first aid kit',
    'safe',
    'safety card',
    'security sytem',
    'smoker detector',
    'foosball',
    'indoor jacuzzi',
    'outdoor jacuzzi',
    'ping-pong table',
    'pool table',
    'dry sauna(private)',
    'fitness room(private)',
    'swimming pool-indoor & heated(private)',
    'steam sauna(private)',
    'swimming pool-indoor & heated(shared)',
    'swimming pool-outdoor & heated(shared)',
    'steam sauna(shared)',
    'swimming pool',
  ].map((name) => ({ name })),
);
