# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lodgly_10
    ports:
        - 3306:3306
    expose:
      # Opens port 3306 on the container
      - '3306'