const TABLE_NAME = 'rates';

exports.up = (knex) => knex.schema.createTable(TABLE_NAME, (table) => {
  table.increments('id');
  table.integer('unitTypeId').notNull().unsigned();
  table.string('rateName');
  table.string('currency');
  table.integer('price_per_night');
  table.integer('minimum_stay');
  table.integer('discount_price_per_week');
  table.integer('discount_price_per_month');
  table.integer('discount_price_custom_nights');
  table.integer('price_on_monday');
  table.integer('price_on_tuesday');
  table.integer('price_on_wednesday');
  table.integer('price_on_thursday');
  table.integer('price_on_friday');
  table.integer('price_on_saturday');
  table.integer('price_on_sunday');
  table.integer('minimum_stay_on_monday');
  table.integer('minimum_stay_on_tuesday');
  table.integer('minimum_stay_on_wednesday');
  table.integer('minimum_stay_on_thursday');
  table.integer('minimum_stay_on_friday');
  table.integer('minimum_stay_on_saturday');
  table.integer('minimum_stay_on_sunday');
  table.integer('extra_charge_on_guest');
  table.integer('extra_guest');
  table.integer('short_stay');
  table.integer('extra_chage_on_stay');
  table.boolean('checkIn_on_monday');
  table.boolean('checkIn_on_tuesday');
  table.boolean('checkIn_on_wednesday');
  table.boolean('checkIn_on_thursday');
  table.boolean('checkIn_on_friday');
  table.boolean('checkIn_on_saturday');
  table.boolean('checkIn_on_sunday');
  table.boolean('checkOut_on_monday');
  table.boolean('checkOut_on_tuesday');
  table.boolean('checkOut_on_wednesday');
  table.boolean('checkOut_on_thursday');
  table.boolean('checkOut_on_friday');
  table.boolean('checkOut_on_saturday');
  table.boolean('checkOut_on_sunday');
  table.string('tax_status');
  table.integer('tax');
  table.string('notes');
  table.foreign('unitTypeId').references('unitType.id').onUpdate('CASCADE').onDelete('CASCADE');
  table.timestamp('created_at').notNull().defaultTo(knex.raw('CURRENT_TIMESTAMP'));
  table.timestamp('updated_at').notNull().defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
});

exports.down = (knex) => knex.schema.dropTable(TABLE_NAME);
