const TABLE_NAME = 'bookingV2';

exports.up = (knex) => knex.schema.createTable(TABLE_NAME, (table) => {
  table.increments('id');
  table.integer('userId').notNull().unsigned();
  table.integer('unitTypeId').notNull().unsigned();
  table.integer('bookedUnit');
  table.string('propertyName');
  table.string('unitName');
  table.date('startDate');
  table.date('endDate');
  table.date('optionalDate');
  table.string('acknowledge').defaultTo('confirmed');
  table.string('channel');
  table.decimal('commission');
  table.integer('adult');
  table.integer('children1');
  table.integer('children2');
  table.string('guest');
  table.integer('noOfGuest').defaultTo(0);
  table.string('notes1');
  table.string('notes2');
  table.decimal('perNight');
  table.integer('night');
  table.decimal('amt');
  table.string('discountType');
  table.decimal('discount');
  table.decimal('accomodation');
  table.string('noOfservices');
  table.decimal('totalAmount');
  table.decimal('deposit');
  table.string('depositType');
  table.string('status').defaultTo('booked');
  table.string('statusColour').defaultTo('red');
  table.string('currency').defaultTo('€');
  table.boolean('checkIn').defaultTo('0');
  table.boolean('paid').defaultTo('0');
  table.timestamp('created_at').notNull().defaultTo(knex.raw('CURRENT_TIMESTAMP'));
  table.timestamp('updated_at').notNull().defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
  table.foreign('userId').references('users.id').onUpdate('CASCADE').onDelete('CASCADE');
  table.foreign('unitTypeId').references('unitTypeV2.id').onUpdate('CASCADE').onDelete('CASCADE');
});

exports.down = (knex) => knex.schema.dropTable(TABLE_NAME);
