const TABLE_NAME = 'seasonRates';

exports.up = (knex) => knex.schema.createTable(TABLE_NAME, (table) => {
  table.increments('id');
  table.integer('unitTypeId').notNull().unsigned();
  table.string('seasonRateName');
  table.date('startDate');
  table.date('endDate');
  table.integer('price_per_night').defaultTo(0);
  table.integer('minimum_stay').defaultTo(0);
  table.integer('discount_price_per_week').defaultTo(0);
  table.integer('discount_price_per_month').defaultTo(0);
  table.integer('discount_price_custom_nights').defaultTo(0);
  table.integer('customNights').defaultTo(0);
  table.integer('price_on_monday').defaultTo(0);
  table.integer('price_on_tuesday').defaultTo(0);
  table.integer('price_on_wednesday').defaultTo(0);
  table.integer('price_on_thursday').defaultTo(0);
  table.integer('price_on_friday').defaultTo(0);
  table.integer('price_on_saturday').defaultTo(0);
  table.integer('price_on_sunday').defaultTo(0);
  table.integer('minimum_stay_on_monday').defaultTo(0);
  table.integer('minimum_stay_on_tuesday').defaultTo(0);
  table.integer('minimum_stay_on_wednesday').defaultTo(0);
  table.integer('minimum_stay_on_thursday').defaultTo(0);
  table.integer('minimum_stay_on_friday').defaultTo(0);
  table.integer('minimum_stay_on_saturday').defaultTo(0);
  table.integer('minimum_stay_on_sunday').defaultTo(0);
  table.integer('extra_charge_on_guest').defaultTo(0);
  table.integer('extra_guest').defaultTo(0);
  table.integer('short_stay').defaultTo(0);
  table.integer('extra_chage_on_stay').defaultTo(0);
  table.boolean('checkIn_on_monday');
  table.boolean('checkIn_on_tuesday');
  table.boolean('checkIn_on_wednesday');
  table.boolean('checkIn_on_thursday');
  table.boolean('checkIn_on_friday');
  table.boolean('checkIn_on_saturday');
  table.boolean('checkIn_on_sunday');
  table.boolean('checkOut_on_monday');
  table.boolean('checkOut_on_tuesday');
  table.boolean('checkOut_on_wednesday');
  table.boolean('checkOut_on_thursday');
  table.boolean('checkOut_on_friday');
  table.boolean('checkOut_on_saturday');
  table.boolean('checkOut_on_sunday');
  table.foreign('unitTypeId').references('unitType.id').onUpdate('CASCADE').onDelete('CASCADE');
  table.timestamp('created_at').notNull().defaultTo(knex.raw('CURRENT_TIMESTAMP'));
  table.timestamp('updated_at').notNull().defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
});

exports.down = (knex) => knex.schema.dropTable(TABLE_NAME);
